apiVersion: v1
kind: Pod
metadata:
  name: vadd-6gb-0 #cointainer name
spec:
  hostIPC: true # 
  securityContext:
    runAsUser: 0
  containers:
    - name: vadd
      image: "nvcr.io/nvidia/pytorch:23.10-py3"
      command: ["bash", "-c", "while true; do echo 'running ...' && sleep 60; done"]
      resources:
        limits:
          nvidia.com/gpu-6gb: 1 # 
      env:
        - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
          value: "60"
